### ISSUE TITLE
Log logistic function

### ISSUE THREAD

**Issue by scepeda78** [jszymon/pacal#11]
Hi, it's a lovely and nice library. Is it too difficult to add other functions such as log logistic? If following the other examples of distribution, would it be possible to do it?

**Comment by jszymon** [comment]
Hi Sebastian,

Thanks for kind words about PaCAL. Sure, other functions/distributions can be added (some are easy, some harder ;).

Do you mean log-logistic distribution? I could not find log logistic function...  Let me know, I'll try to add it.

Szymon

**Comment by scepeda78** [comment]
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.fisk.html

The other name is Fisk it seems

From what I've read it's compatible or not with python 3?

Many thanks for the help!

Rgds
Sebastian

**Comment by jszymon** [comment]
Here you are, log-logistic distribution has been added in the master branch.
Note that you need to use the current version from git.

You can also use FunDistr to define a distribution using arbitrary function as pdf.

**Comment by scepeda78** [comment]
Hi! First of all many thanks for the help!!. I cannot see the code in the standard_dist.py, only the init_py and the test file were committed, it seemsss

**Comment by jszymon** [comment]
Ooops, my mistake ;)  Committed now.

**Comment by scepeda78** [comment]
Now it works perfect, many thanks for the help!!!
