### ISSUE TITLE
Inverse CDF (PPF) fails closer to zero (outputs nan)

### ISSUE THREAD

**Issue by shashankrao** [jszymon/pacal#5]
Hi,

Another issue that I found on Pacal (built from master after your current fix) running on Python3.

Setup: Define a variable dist ~ N(2,1). Use pacal functions to get the `cdf`, and then the `ppf` using `cdf.invfun`. 

```
dist = pacal.NormalDistr(2, 1)
cdf = dist.get_piecewise_cdf()
ppf = cdf.invfun(rangeY=None)
```

Then, I try to calculate the `ppf` are various points:

```
[ppf(x/10) for x in range(11)]
```

This outputs:

```
[0,
 nan,
 1.1583787664270961,
 1.4755994872920493,
 1.7466528968641983,
 1.999999999999999,
 2.2533471031358014,
 2.5244005127079476,
 2.841621233572903,
 3.281551558981633,
 9.952639588985395]
```

I see that it's failing closer to zero. When I try to plot it, I see this:

```
ppf.plot()
```

Output:
![image](https://user-images.githubusercontent.com/2066842/42175967-30f8fb50-7ddc-11e8-9089-d26a3ccf2028.png)

For reference, this is the expected output I get by using `scipy`:

```
from scipy.stats import norm
[norm.ppf(x/10, loc=2,scale=1) for x in range(11)]
```

```
[-inf,
 0.7184484344553996,
 1.1583787664270857,
 1.475599487291959,
 1.7466528968642003,
 2.0,
 2.2533471031357997,
 2.5244005127080404,
 2.8416212335729143,
 3.2815515655446004,
 inf]
```

Let me know if you need any other information! Thanks again for supporting this package in Python3.

**Comment by jszymon** [comment]
I partially fixed the problem: it works but there is a loss of accuracy
towards the left end.

Interpolated inverse cdf functions are not yet very accurate. Try:

[cdf.inverse(x/10) for x in range(11)]

which computes the inverse explicitly at every point. It will give better
results at the moment.

**Comment by jszymon** [comment]
The problem has now been fixed.
