### ISSUE TITLE
An import "numpy.fft.fftpack" is missing

### ISSUE THREAD

**Issue by michael-ziedalski** [jszymon/pacal#8]
Hello, all. After installing Pacal on a Python 3.7.3, Mac OS 10.11 environment, I was eager to start using it, but I encounter an error when importing.

`import pacal as co` gives back a `ModuleNotFoundError: No module named 'numpy.fft.fftpack'`.

Is there any potentially easy fix for this? This seems like one of the only convolution libraries in Python, so I hope this works.

**Comment by michael-ziedalski** [comment]
After reading numpy's [release notes](https://github.com/numpy/numpy/blob/a9bb517554004cf2ce7a4be93bcbfb63ee149844/doc/source/release/1.17.0-notes.rst), in the `utils.py` files, I ended up changing `from numpy.fft.fftpack import fft, ifft` to `from numpy.fft.pocketfft import fft, ifft`, and operations on Normal distributions seem to work.

**Comment by Arech** [comment]
Dear Google, please tell anyone concerned, that in order to get rid of `ModuleNotFoundError: No module named 'numpy.fft.fftpack'` in Pacal 1.6 with current-latest numpy v.1.19.2, line 32 in `pacal\utils.py` should be changed to `from numpy.fft import fft, ifft`. Then it works.

**Comment by jszymon** [comment]
Thanks for the comment.  Actually the issue has been fixed in master in February.  Will be included in the next release.
