### ISSUE TITLE
On computing Pr( Y-const1 < X <= Y+const2) for random vars X and Y

### ISSUE THREAD

**Issue by Arech** [jszymon/pacal#9]
Dear authors of Pacal, thank you for such an interesting tool.

I was playing with Pacal trying to compute for two random vars X and Y the probablity P( Y-const1 < X <= Y+const2) and it seems I stuck into some weird behaviour... (edited:) Most likely I'm doing something wrong, but I can't find what is it. Could someone please help?

#### The context of the use-case under a spoiler

<details>
  <summary>Click here to unroll (you may skip that section entirely, it's just to understand a context of the task)</summary>

Imagine a game of bowling. There is a fixed width lane (s), on one side of it there's a pin of width (f) placed according to some distribution D1 and there's a bowling ball of width (h) thrown parallel to the lane boundaries (ball's position is also some random distribution D2):

```
=upper-lane-boundary============================
 ^                          o <-- bowling pin of width f
 |   ball width h --> O
 |
 lane width S
 |
 v
=lower-lane-boundary============================

```

The question is what's the probability of ball hitting the pin?

If D1 and D2 are uniform distributions, it's easy to calculate the probability analytically. So knowing the answer beforehand, I started to test Pacal:

```python
from pacal import *

s=20
f=2
h=3

# ball is a coordinate of topmost point of the ball. Lowmost is (ball+h)
ball = UniformDistr(0, s-h)

# pin is a coordinate of topmost point of the pin. Lowmost is (pin+f)
pin = UniformDistr(0, s-f)

# when ball coordinate satisfies `pin-h < ball <= pin+f` inequality, ball hits the pin, so we
# need to find probability of that: P(pin-h < ball <= pin+f) which can be calculated using CDF
# as `ball.cdf(pin+f) - ball.cdf(pin-h)`.
print( ball.cdf(pin+f) - ball.cdf(pin-h) )

# and that line fails (details below).
# it probably anyway "incorrect" because of how Pacal handles dependent variables
# but I can't find a way how to rephrase it.

# btw, computing just P(ball <= pin+f) which doesn't introduce dependencies
# also fails because of the same reason
print( ball.cdf(pin+f) )

```
Here's the error just for the case, but that not really why I started that issue 

```
  File "D:\utils\Anaconda3\lib\site-packages\pacal\distr.py", line 129, in cdf
    return self.get_piecewise_cdf()(x)

  File "D:\utils\Anaconda3\lib\site-packages\pacal\segments.py", line 997, in __call__
    ind = ((x>=seg.a) & (x<seg.b))

  TypeError: '>=' not supported between instances of 'ShiftedScaledDistr' and 'float'
```
(I guess it is because cdf() doesn't expect it's argument to be a distribution, rather than a float)
</details>

Ok, leave it as it is and try to calculate the probability in an old fashioned way via integration of joint pdf of distribution.

#### The issue

I tried to compute my probability directly by integrating pdf's of distribution and I obtain wrong results when I'm using pdf's given by Pacal, thought pdf's from sympy.stats or when coded directly by hand are fine.

Here's the full code:

```python
import sympy as sp
import sympy.stats as st
import pacal as pc
import timeit
import scipy.integrate as scpi

ttrun = 1

s=20
f=2
h=3

anProb = 1 - (s-f-h)**2/((s-f)*(s-h))

def showres(n,pr,tm):
    if type(pr) is tuple:
        print('{0}-{1:.06f}s: computed={2}, an={3:.06f}'.format(n, tm, pr, anProb))
    else:
        print('{0}-{1:.06f}s: computed={2} ({3:.06f}), an={4:.06f}'.format(n, tm, pr,\
            pr if type(pr) is float else float(pr), anProb))

'''
ball = UniformDistr(0, s-h)
pin = UniformDistr(0,s-f)

print( ball.cdf(pin+f)-ball.cdf(pin-h) )
print( ball.cdf(pin+f) )
# doesn't work, should integrate by hand
'''

pr=0.0

def pacal_scipy_numint():
    global pr
    ball = pc.UniformDistr(0, s-h)
    pin = pc.UniformDistr(0,s-f)
    
    ball_pdf = ball.get_piecewise_pdf()
    pin_pdf = pin.get_piecewise_pdf()
    
    fxy = lambda x,y: ball.pdf(x)*pin.pdf(y)
    #fxy = lambda x,y: ball_pdf(x)*pin_pdf(y)   #same result

    ###### important
    #fxy2 = ball_pdf*pin_pdf
    #fxy = lambda x,y: fxy2(x)  #this is obviously wrong pdf, but it produces the same result as before, so most likely I'm doing something wrong, but what exactly?
    ###### /important
    
    #fxy = lambda x,y: 1/((s-h)*(s-f))   # works correctly (need to subtract 2 more integrals to make equal with anProb)
    
    pr = scpi.dblquad(fxy, 0, s-f, lambda y: y-h, lambda y: y+f)
    
    #def bnd_x(y):
    #    return [y-h, y+f]
    #pr = scpi.nquad(fxy, [bnd_x, [0, s-f]])  # same result
    
    return pr

bht = timeit.timeit(pacal_scipy_numint, number=ttrun)/ttrun
showres('pacal_scipy_numint', pr, bht)

#############################

def sympy_byhand():
    global pr
    #compute joint pdf and cdf value by hand
    ball_pdf = 1/(s-h)
    pin_pdf = 1/(s-f)
    fxy = ball_pdf*pin_pdf
    
    x = sp.Symbol('x')
    y = sp.Symbol('y')
    
    # need either to update pdfs to make it zero in out-of-domain area or to subtract false tails
    pr = sp.integrate(fxy,(x,y-h,y+f),(y,0,s-f)) \
        - sp.integrate(fxy,(x,y-h,0),(y,0,h)) \
           - sp.integrate(fxy,(x,s-h,y+f),(y,s-f-h,s-f))
    return pr

bht = timeit.timeit(sympy_byhand, number=ttrun)/ttrun
showres('sympy_byhand', pr, bht)

#############################

def sympy_stat():
    global pr
    x = sp.Symbol('x')
    y = sp.Symbol('y')
    
    od = st.Uniform('od', 0, s-h)
    fd = st.Uniform('od', 0, s-f)
    
    opdf = st.density(od)(x)
    fpdf = st.density(fd)(y)
    
    pr = sp.integrate(opdf * fpdf, (x,y-h,y+f),(y,0,s-f))
    return pr

bht = timeit.timeit(sympy_stat, number=ttrun)/ttrun
showres('sympy_stat', pr, bht)
```

The function that uses Pacal is `pacal_scipy_numint()`. Note the comments - I tried .pdf(), .get_piecewise_pdf() and a direct pdf specification. Only the latter works correctly.

Here's the results of run:

```
pacal_scipy_numint-1.638697s: computed=(0.014537426519383745, 1.4811726520553338e-08), an=0.264706
sympy_byhand-0.070829s: computed=0.264705882352941 (0.264706), an=0.264706
sympy_stat-1.090513s: computed=9/34 (0.264706), an=0.264706
```

Only `pacal_scipy_numint()` returns wrong result, all other implementations are fine... It looks that I missed something (it's quite possible, I'm newbie to python), but I don't get what's wrong.

Any ideas what is going on?

Thank you for your time.

---------

apnd: it's definitely my fault somewhere with integration, because even when I set `fxy = lambda x,y: float((x>=0) & (x<=(s-h)) & (y>=0) & (y<=(s-f)))/((s-h)*(s-f))` it gives the same incorrect result. I guess I'm overheated heavily))), but I still don't see what's wrong. Only unconstrained `fxy = lambda x,y: 1/((s-h)*(s-f))` with subsequent subtraction (like in `sympy_byhand`) works properly.

**Comment by Arech** [comment]
Oh heck, I forgot how numeric integration works... It's an artifact of these pdfs discontinuities at edges. That's why unconstrained quasy-pdf works and constrained - doesn't.
Really sorry to bother. Closing issue...

**Comment by Arech** [comment]
forget to say, should anyone find this text with similar problem, the solution is to handle discontinuities properly in `pacal_scipy_numint()`. Instead of integration with `dblquad()` more flexible `nquad()` function must be used with preset special attention points:

```python
def bnd_x(y):
        return [y-h, y+f]
    pr = scpi.nquad(fxy, [bnd_x, [0, s-f]], opts={"points":[0,s-h,s-f]})
```

Now everything is perfect ;)

**Comment by jszymon** [comment]
Hi Arech,

thanks for nice words on PaCal and an interesting example.  Actually, PaCal is designed primarily for arithmetic operations, so using them is better tested.  I think the code below solves your problem.  That said it would be nice to be able to take a cdf (treated as a function) of an rv.  Maybe in some future release...

```
from pacal import *

s=20
f=2
h=3

ball = UniformDistr(h/2, s-h/2)
pin = UniformDistr(f/2, s-f/2)

d = abs(ball-pin)
print(d.cdf((f+h)/2))
```

**Comment by Arech** [comment]
Thanks for commenting! Errmm... I kind of feel a little bit ashamed how easily my task could be solved should I think about it the more natural and PaCal-ish way, just like you did))) But that doesn't matter actually.. It is really impressive approach and I very much like it! PaCal seems to offer a great and very natural way to deal with probabilities, and I think it deserves MUCH more recognition in society that it meets now (it looks like it's hardly known at all!)

BTW, I guess I have a real bug report now: when running your code I got `TypeError: 'numpy.float64' object cannot be interpreted as an integer` inside `numpy.linspace` implementation. It turns out, that it is caused at `pacal/integration.py@233` (and same pattern at line 245, with a `numpy.logspace()` function argument `number_of_intervals`. That argument must be an integer at the current `numpy` version, but actually it's a ceil()-ed float. So to fix it, one should change line 232 (and 244) that computes `number_of_intervals` var to cast the variable directly to an integer after taking `ceil()`:
```python
#number_of_intervals = ceil(log10(exp_wide)/log10(wide_cond))
number_of_intervals = int(ceil(log10(exp_wide)/log10(wide_cond)))
```

The good point is however that after the fix the code works correctly, and it is not only the fastest code out of 3 more generic versions I have made earlier, but it's roughly 4 times faster than the previous fastest routine)) Impressive too!

**Comment by Arech** [comment]
Oh, and by the way, why did you choose a 'centered' representation of the entities ( `UniformDistr(h/2, s-h/2)` ) instead of seemingly equvalent non-centered `UniformDistr(0, s-h)` ? Non-centered variant returns wrong result (starting in third decimal point), but I don't get - why that happens? And what should I be aware of when working on my own?

**Comment by Arech** [comment]
Oh heck! It's obvious why!
```python
ball = pc.UniformDistr(0, s-h)
pin = pc.UniformDistr(0, s-f)

d = ball-pin
pr = d.cdf(f) - d.cdf(-h)
```
I love probability theory!))

**Comment by jszymon** [comment]
Hi Arech,

thanks for noticing the bug with logspace.  Actually it has been (hopefully) fixed in the master branch some time ago.  Actually a few days ago I pushed out a minor release, can you check if everything works?

Yes, I picked h/2 and f/2 to get everytihng centered and to be able to use abs.

Best, Szymon

**Comment by Arech** [comment]
Hello Szymon,

I've just fetched new version 1.6.1 from `pip`, - works fine in my use-cases, thanks for your work!

One remark: I tried "Parallel circuit of two resistors" example
```python
import pacal as pc

R1 = pc.UniformDistr(0.5, 1.5)
R2 = pc.UniformDistr(1.5, 2.5)
pr = pc.PiCopula(marginals = [R1, R2])
M = pc.TwoVarsModel(pr, R1 * R2 / (R1 + R2))
R_equiv = M.eval()
R_equiv.plot(linewidth = 2.0, color = 'k')
plt.show()
```
and it spawns a message `UserWarning: Warning: arguments treated as independent`
(haven't tried on the v1.6 though)

Shouldn't the message be suppressed (or even non-relevant) here, because we explicitly described the variables dependency?


And 


Regarding my interest to the "Parallel circuit of two resistors" example... (it's is mostly far beyond this issue tracker, so feel free to ignore if you want (I'm just catching a possible opportunity to learn from probability theory professional, but I'm totally ok if you will ignore it)... I tried to generalize the task described in the first post to the case of 2+ pins of different sizes (let f1 is width of the first pin, f2 - second, etc..) and stuck completely with it... It seems to me it's impossible to describe resulting distribution without using more than one occurrence of corresponding pin (or ball) distribution variable. Once we are doing it - we are going to get proper results that applicable only to the case of independent rv-s with the same distribution. I.e. the following code is totally wrong:

```python
import pacal as pc

ball = pc.UniformDistr(h/2, s-h/2)
pin1 = pc.UniformDistr(f1/2, s-f1/2)
pin2 = pc.UniformDistr(f2/2, s-f2/2)
d = abs( pc.CondGtDistr( ball - pc.min(pin1,pin2) ,0) + pc.CondLtDistr(ball - pc.max(pin1,pin2),0) )
print( d.cdf((min(f1,f2)+h)/2.0) )
```

`abs( pc.CondGtDistr( ball - pc.min(pin1,pin2) ,0) + pc.CondLtDistr(ball - pc.max(pin1,pin2),0) )` is definitely wrong distribution for the task, at least because `ball`, `pin1` and `pin2` in the first addendum describes rv-s that are independent of similar rv-s in the second addendum. But at least the code works.

It has just called to my mind about "Parallel circuit of two resistors" example and then I tried to describe some distributions dependency the way it was done in the example: so I just replaced the line `d = abs( pc.CondGtDistr( ball - pc.min(pin1,pin2) ,0) + pc.CondLtDistr(ball - pc.max(pin1,pin2),0) )` with lines:

```python
pr = pc.PiCopula(marginals = [pin1, pin2])
M = pc.TwoVarsModel(pr, abs( pc.CondGtDistr( ball - pc.min(pin1,pin2) ,0) + pc.CondLtDistr(ball - pc.max(pin1,pin2),0) ) )
d = M.eval()
```

(yeah, I forgot about `ball` var here, but let's pretend it's ok)
But now it totally fails:
```
M = pc.TwoVarsModel(pr, abs( pc.CondGtDistr( ball - pc.min(pin1,pin2) ,0) + pc.CondLtDistr(ball - pc.max(pin1,pin2),0) ) )
  File "D:\utils\Anaconda3\lib\site-packages\pacal\depvars\models.py", line 473, in __init__
    self.fun_alongx = eq_solve(self.symop, z, y)[0]
IndexError: list index out of range
```

**Comment by Arech** [comment]
Hello Szymon,

I've just fetched new version 1.6.1 from `pip`, - works fine in my use-cases, thanks for your work!

One remark: I tried "Parallel circuit of two resistors" example
```python
import pacal as pc

R1 = pc.UniformDistr(0.5, 1.5)
R2 = pc.UniformDistr(1.5, 2.5)
pr = pc.PiCopula(marginals = [R1, R2])
M = pc.TwoVarsModel(pr, R1 * R2 / (R1 + R2))
R_equiv = M.eval()
R_equiv.plot(linewidth = 2.0, color = 'k')
plt.show()
```
and it spawns a message `UserWarning: Warning: arguments treated as independent`
(haven't tried on the v1.6 though)

Shouldn't the message be suppressed (or even non-relevant) here, because we explicitly described the variables dependency?

=======

Regarding my interest to the "Parallel circuit of two resistors" example... (it's is mostly far beyond this issue tracker, so feel free to ignore if you want (I'm just catching a possible opportunity to learn from probability theory professional, but I'm totally ok if you will ignore it)... I tried to generalize the task described in the first post to the case of 2+ pins of different sizes (let f1 is width of the first pin, f2 - second, etc..) and stuck completely with it... So if you have any idea how to do it and may share your thoughts I'll be very grateful for it!

(I prematurely posted here a comment (github reacted on some weird keystroke) that mentioned another possible issue, but actually it was totally my mistake, so I deleted it, sorry to bother)

**Comment by jszymon** [comment]
regarding "UserWarning: Warning: arguments treated as
independent": the expression is constructed just like any other
pacal expression so currently I see no easy way of fixing this...

regarging more than two pins/balls: the right expression seems to
me

min_{i in balls}min_{j in pins} abs(i-j)

after which you would get its cdf.  Unfortunately this is not
currently possible in PaCAL since all abs(i-j) become dependent
and min is not supported in the dependent variables inference.

Best,

Szymon

**Comment by Arech** [comment]
I see... I thought there might be a chance that I don't understand something and there's some way to calc it with PaCal... Thanks for confirming! Anyway, it's still a great tool.
